return {
    -- Front Row Left
    Inferium_2 = {row="front",pos="1",dir="left",light=peripheral.wrap("redstone_relay_73")},
    Inferium_4 = {row="front",pos="2",dir="left",light=peripheral.wrap("redstone_relay_74")},
    Sheep = {row="front",pos="3",dir="left",light=peripheral.wrap("redstone_relay_75")},
    Soulium = {row="front",pos="4",dir="left",light=peripheral.wrap("redstone_relay_76")},
    Iron = {row="front",pos="5",dir="left",light=peripheral.wrap("redstone_relay_77")},
    Coal = {row="front",pos="6",dir="left",light=peripheral.wrap("redstone_relay_78")},
    Water = {row="front",pos="7",dir="left",light=peripheral.wrap("redstone_relay_79")},
    Dirt = {row="front",pos="8",dir="left",light=peripheral.wrap("redstone_relay_80")},
    Fire = {row="front",pos="9",dir="left",light=peripheral.wrap("redstone_relay_81")},
    Cyanite = {row="front",pos="10",dir="left",light=peripheral.wrap("redstone_relay_82")},
    Stone = {row="front",pos="11",dir="left",light=peripheral.wrap("redstone_relay_83")},
    Darkstone = {row="front",pos="12",dir="left",light=peripheral.wrap("redstone_relay_84")},
    Lead = {row="front",pos="13",dir="left",light=peripheral.wrap("redstone_relay_85")},
    Zinc = {row="front",pos="14",dir="left",light=peripheral.wrap("redstone_relay_86")},
    ["Refined Obsidian"] = {row="front",pos="15",dir="left",light=peripheral.wrap("redstone_relay_87")},
    CopperAlloy = {row="front",pos="16",dir="left",light=peripheral.wrap("redstone_relay_88")},
    -- Front Row Right
    Inferium_1 = {row="front",pos="1",dir="right",light=peripheral.wrap("redstone_relay_1")},
    Inferium_3 = {row="front",pos="2",dir="right",light=peripheral.wrap("redstone_relay_89")},
    Wood = {row="front",pos="3",dir="right",light=peripheral.wrap("redstone_relay_90")},
    Redstone = {row="front",pos="4",dir="right",light=peripheral.wrap("redstone_relay_91")},
    Gold = {row="front",pos="5",dir="right",light=peripheral.wrap("redstone_relay_92")},
    Diamond = {row="front",pos="6",dir="right",light=peripheral.wrap("redstone_relay_93")},
    ["Nether Quartz"] = {row="front",pos="7",dir="right",light=peripheral.wrap("redstone_relay_94")},
    Skeleton = {row="front",pos="8",dir="right",light=peripheral.wrap("redstone_relay_95")},
    Amethyst = {row="front",pos="9",dir="right",light=peripheral.wrap("redstone_relay_96")},
    Constantan = {row="front",pos="10",dir="right",light=peripheral.wrap("redstone_relay_97")},
    ["Wither Skeleton"] = {row="front",pos="11",dir="right",light=peripheral.wrap("redstone_relay_98")},
    Prismarine = {row="front",pos="12",dir="right",light=peripheral.wrap("redstone_relay_99")},
    Spider = {row="front",pos="13",dir="right",light=peripheral.wrap("redstone_relay_100")},
    ["Niotic Crystal"] = {row="front",pos="14",dir="right",light=peripheral.wrap("redstone_relay_101")},
    Dye = {row="front",pos="15",dir="right",light=peripheral.wrap("redstone_relay_102")},
    Nether = {row="front",pos="16",dir="right",light=peripheral.wrap("redstone_relay_103")},
    -- Right Row Right
    Emerald = {row="right",pos="1",dir="right",light=peripheral.wrap("redstone_relay_103")},
    Nature = {row="right",pos="2",dir="right",light=peripheral.wrap("redstone_relay_104")},
    Glowstone = {row="right",pos="3",dir="right",light=peripheral.wrap("redstone_relay_105")},
    ["End"] = {row="right",pos="4",dir="right",light=peripheral.wrap("redstone_relay_106")},
    Netherite = {row="right",pos="5",dir="right",light=peripheral.wrap("redstone_relay_107")},
    Honey = {row="right",pos="6",dir="right",light=peripheral.wrap("redstone_relay_108")},
    Allthemodium = {row="right",pos="7",dir="right",light=peripheral.wrap("redstone_relay_109")},
    Cow = {row="right",pos="8",dir="right",light=peripheral.wrap("redstone_relay_110")},
    ["Azure Silver"] = {row="right",pos="9",dir="right",light=peripheral.wrap("redstone_relay_111")},
    ["Black Quartz"] = {row="right",pos="10",dir="right",light=peripheral.wrap("redstone_relay_112")},
    ["Crimson Iron"] = {row="right",pos="11",dir="right",light=peripheral.wrap("redstone_relay_113")},
    Entro = {row="right",pos="12",dir="right",light=peripheral.wrap("redstone_relay_114")},
    Kivi = {row="right",pos="13",dir="right",light=peripheral.wrap("redstone_relay_115")},
    ["Sky Steel"] = {row="right",pos="14",dir="right",light=peripheral.wrap("redstone_relay_116")},
    ["Unexplored Wood"] = {row="right",pos="15",dir="right",light=peripheral.wrap("redstone_relay_117")},
    Unobtainium = {row="right",pos="16",dir="right",light=peripheral.wrap("redstone_relay_118")},
    -- Right Row Left
    -- Back Row Right
    -- Back Row Left
    -- Left Row Right
    -- Left Row Left
    Earth = {row="left",pos="1",dir="left",light=peripheral.wrap("redstone_relay_88")},
    Air = {row="left",pos="2",dir="left",light=peripheral.wrap("redstone_relay_119")},
    Ice = {row="left",pos="3",dir="left",light=peripheral.wrap("redstone_relay_120")},
    Deepslate = {row="left",pos="4",dir="left",light=peripheral.wrap("redstone_relay_121")},
    Armadillo = {row="left",pos="5",dir="left",light=peripheral.wrap("redstone_relay_122")},
    Brass = {row="left",pos="6",dir="left",light=peripheral.wrap("redstone_relay_123")},
    Pig = {row="left",pos="7",dir="left",light=peripheral.wrap("redstone_relay_124")},
    Silicon = {row="left",pos="8",dir="left",light=peripheral.wrap("redstone_relay_125")},
    Soularium = {row="left",pos="9",dir="left",light=peripheral.wrap("redstone_relay_126")},
    ["Lapis Lazuli"] = {row="left",pos="10",dir="left",light=peripheral.wrap("redstone_relay_127")},
    ["Grains of Infinity"] = {row="left",pos="11",dir="left",light=peripheral.wrap("redstone_relay_128")},
    Uraninite = {row="left",pos="12",dir="left",light=peripheral.wrap("redstone_relay_129")},
    Steeleaf = {row="left",pos="13",dir="left",light=peripheral.wrap("redstone_relay_130")},
    Vibranium = {row="left",pos="14",dir="left",light=peripheral.wrap("redstone_relay_131")},
    ["Xychorium Gem"] = {row="left",pos="15",dir="left",light=peripheral.wrap("redstone_relay_132")},
    Coral = {row="left",pos="16",dir="left",light=peripheral.wrap("redstone_relay_133")}
}
