return {
    -- Front Row Left
    Inferium = {row="front",pos="1",dir="left",light=peripheral.wrap("redstone_relay_73")},
    Nether Star = {row="front",pos="2",dir="left",light=peripheral.wrap("redstone_relay_74")},
    Sheep = {row="front",pos="3",dir="left",light=peripheral.wrap("redstone_relay_75")},
    Soulium = {row="front",pos="4",dir="left",light=peripheral.wrap("redstone_relay_76")},
    Iron = {row="front",pos="5",dir="left",light=peripheral.wrap("redstone_relay_77")},
    Coal = {row="front",pos="6",dir="left",light=peripheral.wrap("redstone_relay_78")},
    Water = {row="front",pos="7",dir="left",light=peripheral.wrap("redstone_relay_79")},
    Dirt = {row="front",pos="8",dir="left",light=peripheral.wrap("redstone_relay_80")},
    Fire = {row="front",pos="9",dir="left",light=peripheral.wrap("redstone_relay_81")},
    Cyanite = {row="front",pos="10",dir="left",light=peripheral.wrap("redstone_relay_82")},
    Stone = {row="front",pos="11",dir="left",light=peripheral.wrap("redstone_relay_83")},
    Darkstone = {row="front",pos="12",dir="left",light=peripheral.wrap("redstone_relay_84")},
    Lead = {row="front",pos="13",dir="left",light=peripheral.wrap("redstone_relay_85")},
    Zinc = {row="front",pos="14",dir="left",light=peripheral.wrap("redstone_relay_86")},
    ["Refined Obsidian"] = {row="front",pos="15",dir="left",light=peripheral.wrap("redstone_relay_87")},
    ["Copper Alloy"] = {row="front",pos="16",dir="left",light=peripheral.wrap("redstone_relay_88")},
    -- Front Row Right
    ["Dragon Egg"] = {row="front",pos="1",dir="right",light=peripheral.wrap("redstone_relay_1")},
    ["Awakened Draconium"] = {row="front",pos="2",dir="right",light=peripheral.wrap("redstone_relay_89")},
    Wood = {row="front",pos="3",dir="right",light=peripheral.wrap("redstone_relay_90")},
    Redstone = {row="front",pos="4",dir="right",light=peripheral.wrap("redstone_relay_91")},
    Gold = {row="front",pos="5",dir="right",light=peripheral.wrap("redstone_relay_92")},
    Diamond = {row="front",pos="6",dir="right",light=peripheral.wrap("redstone_relay_93")},
    ["Nether Quartz"] = {row="front",pos="7",dir="right",light=peripheral.wrap("redstone_relay_94")},
    Skeleton = {row="front",pos="8",dir="right",light=peripheral.wrap("redstone_relay_95")},
    Amethyst = {row="front",pos="9",dir="right",light=peripheral.wrap("redstone_relay_96")},
    Constantan = {row="front",pos="10",dir="right",light=peripheral.wrap("redstone_relay_97")},
    ["Wither Skeleton"] = {row="front",pos="11",dir="right",light=peripheral.wrap("redstone_relay_98")},
    Prismarine = {row="front",pos="12",dir="right",light=peripheral.wrap("redstone_relay_99")},
    Spider = {row="front",pos="13",dir="right",light=peripheral.wrap("redstone_relay_100")},
    ["Niotic Crystal"] = {row="front",pos="14",dir="right",light=peripheral.wrap("redstone_relay_101")},
    Dye = {row="front",pos="15",dir="right",light=peripheral.wrap("redstone_relay_102")},
    Nether = {row="front",pos="16",dir="right",light=peripheral.wrap("redstone_relay_103")},
    -- Right Row Right
    Emerald = {row="right",pos="1",dir="right",light=peripheral.wrap("redstone_relay_103")},
    Nature = {row="right",pos="2",dir="right",light=peripheral.wrap("redstone_relay_104")},
    Glowstone = {row="right",pos="3",dir="right",light=peripheral.wrap("redstone_relay_105")},
    ["End"] = {row="right",pos="4",dir="right",light=peripheral.wrap("redstone_relay_106")},
    Netherite = {row="right",pos="5",dir="right",light=peripheral.wrap("redstone_relay_107")},
    Honey = {row="right",pos="6",dir="right",light=peripheral.wrap("redstone_relay_108")},
    Allthemodium = {row="right",pos="7",dir="right",light=peripheral.wrap("redstone_relay_109")},
    Cow = {row="right",pos="8",dir="right",light=peripheral.wrap("redstone_relay_110")},
    ["Azure Silver"] = {row="right",pos="9",dir="right",light=peripheral.wrap("redstone_relay_111")},
    ["Black Quartz"] = {row="right",pos="10",dir="right",light=peripheral.wrap("redstone_relay_112")},
    ["Crimson Iron"] = {row="right",pos="11",dir="right",light=peripheral.wrap("redstone_relay_113")},
    Entro = {row="right",pos="12",dir="right",light=peripheral.wrap("redstone_relay_114")},
    Kivi = {row="right",pos="13",dir="right",light=peripheral.wrap("redstone_relay_115")},
    ["Sky Steel"] = {row="right",pos="14",dir="right",light=peripheral.wrap("redstone_relay_116")},
    ["Unexplored Wood"] = {row="right",pos="15",dir="right",light=peripheral.wrap("redstone_relay_117")},
    Unobtainium = {row="right",pos="16",dir="right",light=peripheral.wrap("redstone_relay_118")},
    -- Right Row Left
    Blaze = {row="right",pos="1",dir="left",light=peripheral.wrap("redstone_relay_149")},
    Obsidian = {row="right",pos="2",dir="left",light=peripheral.wrap("redstone_relay_148")},
    Chicken = {row="right",pos="3",dir="left",light=peripheral.wrap("redstone_relay_147")},
    Squid = {row="right",pos="4",dir="left",light=peripheral.wrap("redstone_relay_146")},
    Fish = {row="right",pos="5",dir="left",light=peripheral.wrap("redstone_relay_145")},
    Slime = {row="right",pos="6",dir="left",light=peripheral.wrap("redstone_relay_144")},
    Turtle = {row="right",pos="7",dir="left",light=peripheral.wrap("redstone_relay_143")},
    Rubber = {row="right",pos="8",dir="left",light=peripheral.wrap("redstone_relay_142")},
    Sulfur = {row="right",pos="9",dir="left",light=peripheral.wrap("redstone_relay_141")},
    Aluminum = {row="right",pos="10",dir="left",light=peripheral.wrap("redstone_relay_140")},
    Salpeter = {row="right",pos="11",dir="left",light=peripheral.wrap("redstone_relay_139")},
    Apatite = {row="right",pos="12",dir="left",light=peripheral.wrap("redstone_relay_138")},
    Marble = {row="right",pos="13",dir="left",light=peripheral.wrap("redstone_relay_137")},
    Limestone = {row="right",pos="14",dir="left",light=peripheral.wrap("redstone_relay_136")},
    Basalt = {row="right",pos="15",dir="left",light=peripheral.wrap("redstone_relay_135")},
    Menril = {row="right",pos="16",dir="left",light=peripheral.wrap("redstone_relay_134")},
    -- Back Row Right
    Breeze = {row="back",pos="1",dir="right",light=peripheral.wrap("redstone_relay_149")},
    Ghast = {row="back",pos="2",dir="right",light=peripheral.wrap("redstone_relay_150")},
    Enderman = {row="back",pos="3",dir="right",light=peripheral.wrap("redstone_relay_151")},
    Steel = {row="back",pos="4",dir="right",light=peripheral.wrap("redstone_relay_152")},
    Nickel = {row="back",pos="5",dir="right",light=peripheral.wrap("redstone_relay_153")},
    Electrum = {row="back",pos="6",dir="right",light=peripheral.wrap("redstone_relay_154")},
    Invar = {row="back",pos="7",dir="right",light=peripheral.wrap("redstone_relay_155")},
    Uranium = {row="back",pos="8",dir="right",light=peripheral.wrap("redstone_relay_156")},
    Ruby = {row="back",pos="9",dir="right",light=peripheral.wrap("redstone_relay_157")},
    Peridot = {row="back",pos="10",dir="right",light=peripheral.wrap("redstone_relay_158")},
    ["HOP Graphite"] = {row="back",pos="11",dir="right",light=peripheral.wrap("redstone_relay_159")},
    ["Dark Steel"] = {row="back",pos="12",dir="right",light=peripheral.wrap("redstone_relay_160")},
    ["Pulsating Iron"] = {row="back",pos="13",dir="right",light=peripheral.wrap("redstone_relay_161")},
    ["Energetic Alloy"] = {row="back",pos="14",dir="right",light=peripheral.wrap("redstone_relay_162")},
    Osmium = {row="back",pos="15",dir="right",light=peripheral.wrap("redstone_relay_163")},
    Fluorite = {row="back",pos="16",dir="right",light=peripheral.wrap("redstone_relay_164")},
    -- Back Row Left
    ["Refined Glowstone"] = {row="back",pos="1",dir="left",light=peripheral.wrap("redstone_relay_180")},
    Knightmetal = {row="back",pos="2",dir="left",light=peripheral.wrap("redstone_relay_181")},
    ["Fiery Ingot"] = {row="back",pos="3",dir="left",light=peripheral.wrap("redstone_relay_182")},
    ["Compressed Iron"] = {row="back",pos="4",dir="left",light=peripheral.wrap("redstone_relay_183")},
    Fluix = {row="back",pos="5",dir="left",light=peripheral.wrap("redstone_relay_184")},
    ["Energized Steel"] = {row="back",pos="6",dir="left",light=peripheral.wrap("redstone_relay_185")},
    ["Blazing Crystal"] = {row="back",pos="7",dir="left",light=peripheral.wrap("redstone_relay_186")},
    Platinum = {row="back",pos="8",dir="left",light=peripheral.wrap("redstone_relay_187")},
    Iridium = {row="back",pos="9",dir="left",light=peripheral.wrap("redstone_relay_188")},
    Enderium = {row="back",pos="10",dir="left",light=peripheral.wrap("redstone_relay_189")},
    ["Vibrant Alloy"] = {row="back",pos="11",dir="left",light=peripheral.wrap("redstone_relay_190")},
    ["End Steel"] = {row="back",pos="12",dir="left",light=peripheral.wrap("redstone_relay_191")},
    Draconium = {row="back",pos="13",dir="left",light=peripheral.wrap("redstone_relay_192")},
    Yellorium = {row="back",pos="14",dir="left",light=peripheral.wrap("redstone_relay_193")},
    ["Spirited Crystal"] = {row="back",pos="15",dir="left",light=peripheral.wrap("redstone_relay_194")},
    ["Nitro Crystal"] = {row="back",pos="16",dir="left",light=peripheral.wrap("redstone_relay_195")},
    -- Left Row Right
    Copper = {row="left",pos="1",dir="right",light=peripheral.wrap("redstone_relay_180")},
    Zombie = {row="left",pos="2",dir="right",light=peripheral.wrap("redstone_relay_179")},
    Creeper = {row="left",pos="3",dir="right",light=peripheral.wrap("redstone_relay_178")},
    Phantom = {row="left",pos="4",dir="right",light=peripheral.wrap("redstone_relay_177")},
    Rabbit = {row="left",pos="5",dir="right",light=peripheral.wrap("redstone_relay_176")},
    Tin = {row="left",pos="6",dir="right",light=peripheral.wrap("redstone_relay_175")},
    Bronze = {row="left",pos="7",dir="right",light=peripheral.wrap("redstone_relay_174")},
    Silver = {row="left",pos="8",dir="right",light=peripheral.wrap("redstone_relay_173")},
    Graphite = {row="left",pos="9",dir="right",light=peripheral.wrap("redstone_relay_172")},
    ["Redstone Alloy"] = {row="left",pos="10",dir="right",light=peripheral.wrap("redstone_relay_171")},
    ["Conductive Alloy"] = {row="left",pos="11",dir="right",light=peripheral.wrap("redstone_relay_170")},
    Ironwood = {row="left",pos="12",dir="right",light=peripheral.wrap("redstone_relay_169")},
    ["Sky Stone"] = {row="left",pos="13",dir="right",light=peripheral.wrap("redstone_relay_168")},
    ["Certus Quartz"] = {row="left",pos="14",dir="right",light=peripheral.wrap("redstone_relay_167")},
    ["Quartz Enriched Iron"] = {row="left",pos="15",dir="right",light=peripheral.wrap("redstone_relay_166")},
    Experience = {row="left",pos="16",dir="right",light=peripheral.wrap("redstone_relay_165")},
    -- Left Row Left
    Earth = {row="left",pos="1",dir="left",light=peripheral.wrap("redstone_relay_88")},
    Air = {row="left",pos="2",dir="left",light=peripheral.wrap("redstone_relay_119")},
    Ice = {row="left",pos="3",dir="left",light=peripheral.wrap("redstone_relay_120")},
    Deepslate = {row="left",pos="4",dir="left",light=peripheral.wrap("redstone_relay_121")},
    Armadillo = {row="left",pos="5",dir="left",light=peripheral.wrap("redstone_relay_122")},
    Brass = {row="left",pos="6",dir="left",light=peripheral.wrap("redstone_relay_123")},
    Pig = {row="left",pos="7",dir="left",light=peripheral.wrap("redstone_relay_124")},
    Silicon = {row="left",pos="8",dir="left",light=peripheral.wrap("redstone_relay_125")},
    Soularium = {row="left",pos="9",dir="left",light=peripheral.wrap("redstone_relay_126")},
    ["Lapis Lazuli"] = {row="left",pos="10",dir="left",light=peripheral.wrap("redstone_relay_127")},
    ["Grains of Infinity"] = {row="left",pos="11",dir="left",light=peripheral.wrap("redstone_relay_128")},
    Uraninite = {row="left",pos="12",dir="left",light=peripheral.wrap("redstone_relay_129")},
    Steeleaf = {row="left",pos="13",dir="left",light=peripheral.wrap("redstone_relay_130")},
    Vibranium = {row="left",pos="14",dir="left",light=peripheral.wrap("redstone_relay_131")},
    ["Xychorium Gem"] = {row="left",pos="15",dir="left",light=peripheral.wrap("redstone_relay_132")},
    Coral = {row="left",pos="16",dir="left",light=peripheral.wrap("redstone_relay_133")}
}
